version: "3.3"
services:
  database:
    container_name: "agenda_db"
    image: "mongo:4.4"
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=agenda
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    volumes:
      - ./database:/data/db
